name: Build and Deploy to Azure

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_APP_SERVER_URL=${{ vars.NEXT_PUBLIC_APP_SERVER_URL }}" >> .env
          echo "NEXT_PUBLIC_APP_SECRET_KEY=${{ vars.NEXT_PUBLIC_APP_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_APP_AWS_S3_STORAGE_URL=${{ vars.NEXT_PUBLIC_APP_AWS_S3_STORAGE_URL }}" >> .env

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build --build-arg NEXT_PUBLIC_APP_SERVER_URL=${{ vars.NEXT_PUBLIC_APP_SERVER_URL }} \
                       --build-arg NEXT_PUBLIC_APP_SECRET_KEY=${{ vars.NEXT_PUBLIC_APP_SECRET_KEY }} \
                       --build-arg NEXT_PUBLIC_APP_AWS_S3_STORAGE_URL=${{ vars.NEXT_PUBLIC_APP_AWS_S3_STORAGE_URL }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/jobcompass-frontend:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/jobcompass-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            sudo docker stop jobcompass-frontend || true
            sudo docker rm jobcompass-frontend || true
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/jobcompass-frontend:latest || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/jobcompass-frontend:latest
            sudo docker run -d --name jobcompass-frontend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/jobcompass-frontend:latest
          EOF
